---

- hosts: minecraft
  become: true

  tasks:
    - name: Install tasks, essential for security
      import_tasks: tasks/essential.yml

    - name: Minecraft server install
      import_tasks: tasks/minecraft-install.yml